---
language: python
python:
  - "2.7"

env:
  matrix: # only serial version of QUIP
    - QUIP_ARCH=linux_x86_64_gfortran
    - QUIP_ARCH=linux_x86_64_gfortran_openmp

git:
  depth: 1

before_install:
  - git clone https://${GITHUB_TOKEN}@github.com/libAtoms/GAP.git src/GAP

  # Make the build directory manually for rules
  - mkdir -p build/${QUIP_ARCH}

  # Copy the rules file (rather than make config)
  - cp travis/Makefile.inc build/${QUIP_ARCH}/Makefile.inc

addons:
  apt:
    update: true
    packages:
    - gfortran
    - libblas-dev
    - liblapack-dev
    - openmpi-bin
    - libopenmpi-dev
    - netcdf-bin
    - libnetcdf-dev
    - libhdf5-serial-dev
    - python-numpy

install: # Compile QUIP, libquip and quippy, if a non-skipped build.
  # stdout is redirected as it generates too much output.
  - pip install ase

  - make > /dev/null
  - make libquip > /dev/null
  - make quippy > /dev/null

script: # Quippy should have built successfully -> start tests
  - make test

stages:
  - documentation
  - test

jobs:
  include:
    - stage: documentation
      python:
        - "2.7"

      env:  # only serial version of QUIP
        - QUIP_ARCH=linux_x86_64_gfortran QUIP_ROOT=/home/travis/build/libAtoms/QUIP

      addons:
        apt:
          update: true
          packages: # pandoc is required for nbconvert; gsl and xpm are for atomeye.
          - gfortran
          - libblas-dev
          - liblapack-dev
          - openmpi-bin
          - libopenmpi-dev
          - netcdf-bin
          - libnetcdf-dev
          - libhdf5-serial-dev
          - python-numpy
          - libgsl0-dev
          - libxpm-dev
          - pandoc

      install: # packages for building docs
        - pip install
            ase
            sphinx
            sphinx-rtd-theme
            nbsphinx
            numpydoc

        # needed to nbconvert ipynb files and to process the rst files
        - pip install 'nbconvert[execute]' 'ipython<6'

        # quippy is working, install it
        - make > /dev/null
        - make install-quippy > /dev/null

        # Install atomeye from src
        # - export QUIP_ROOT=`pwd`  # $HOME/build/$TRAVIS_REPO_SLUG
        - git clone https://github.com/jameskermode/AtomEye.git src/AtomEye
        - cd src/AtomEye/Python
        - python setup.py install
        - cd ../../..

      script:
        - cd doc
        - make html

      deploy:
        provider: pages
        local_dir: doc/_build/html
        skip-cleanup: true
        github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
        keep-history: true
        on:
          branch: public

notifications:
  email:
    - quip-developers@eng.cam.ac.uk

