---
language: python
python:
  - "2.7"

branches:
  only:
    - public

git:
  depth: 1

env:  # only serial version of QUIP
  - QUIP_ARCH=linux_x86_64_gfortran

addons:
  apt:
    update: true
    packages:
    - gfortran
    - libblas-dev
    - liblapack-dev
    - openmpi-bin
    - libopenmpi-dev
    - netcdf-bin
    - libnetcdf-dev
    - libhdf5-serial-dev
    - python-numpy

install:
  - echo "!!!!!!!!!!! hello !!!!!!!!!!!!!!!!!!!!"

stages:
  - test
  - documetation

jobs:
  include:
    - stage: test
      before_install:
        - echo ${QUIP_ARCH}
        - python --version
        - gfortran --version
        - gcc --version
        - g++ --version

        # Make the build directory manually for rules
        - mkdir -p build/${QUIP_ARCH}

        # Copy the rules file (rather than make config)
        - cp travis/Makefile.inc build/${QUIP_ARCH}/Makefile.inc

        - pip install ase

      install: # Compile QUIP, libquip and quippy, if a non-skipped build.
        # stdout is redirected as it generates too much output.
        - make > /dev/null
        - make libquip > /dev/null
        - make quippy > /dev/null

      script: # Quippy should have built successfully -> start tests
        - make test

    - stage: documetation
      python:
        - "2.7"
      env:  # only serial version of QUIP
        - QUIP_ARCH=linux_x86_64_gfortran

      before_install: # pandoc is required for nbconvert; gsl and xpm are for atomeye.
        - sudo apt-get install -y
            libgsl0-dev
            libxpm-dev
            pandoc

        # packages for building docs
        - pip install
            sphinx
            sphinx-rtd-theme
            nbsphinx
            numpydoc

        # needed to nbconvert ipynb files and to process the rst files
        - pip install 'nbconvert[execute]' 'ipython<6'

      install: # quippy is working, install it
        - make install-quippy

        # Install atomeye from src
        - git clone https://github.com/jameskermode/AtomEye.git src/AtomEye
        - cd src/AtomEye/Python && python setup.py install

      script:
        - cd doc; make html
#
#      deploy:
#        provider: pages
#        local_dir: doc/_build/html
#        skip-cleanup: true
#        github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
#        keep-history: true
#        on:
#          branch: master
#
#notifications:
#  email:
#    - quip-developers@eng.cam.ac.uk

