---
language: python
python:
  - "3.6"
env:
  matrix:
    - QUIP_ARCH=linux_x86_64_gfortran QUIP_INC=Makefile.nogap.inc
    - QUIP_ARCH=linux_x86_64_gfortran QUIP_INC=Makefile.inc
    - QUIP_ARCH=linux_x86_64_gfortran_openmp QUIP_INC=Makefile.nogap.inc
    - QUIP_ARCH=linux_x86_64_gfortran_openmp QUIP_INC=Makefile.inc

stages:
  - test
  - name: documentation
    # freezing the python2.7 version fot this at first
    if: branch = archived_py2
  - name: release
    if: branch = public
  - name: docker
    if: branch = public

git:
  depth: 1

addons:
  apt:
    update: true

before_install:
  - sudo apt-get install -y
      gfortran
      libblas-dev
      liblapack-dev
      openmpi-bin
      libopenmpi-dev
      netcdf-bin
      libnetcdf-dev
      libhdf5-serial-dev
      python-numpy

  # Clone the private gap repository using deploy key
  - echo $github_deploy_key | base64 -d > ~/.ssh/github_deploy_key
  - chmod 0600  ~/.ssh/github_deploy_key
  - eval $(ssh-agent -s)
  - ssh-add ~/.ssh/github_deploy_key
  - git clone --depth 1 git@github.com:libAtoms/GAP.git src/GAP
  # Make the build directory manually for rules
  - mkdir -p build/${QUIP_ARCH}
  # Copy the rules file (rather than make config)
  - cp travis/${QUIP_INC} build/${QUIP_ARCH}/Makefile.inc


install:
  - pip install ase

script: # Compile QUIP, libquip and quippy, if a non-skipped build.
  # stdout is redirected as it generates too much output.
  # Quippy should have built successfully -> start tests
  - make
  - make libquip
  - make quippy

  # Sometimes file limit is 64000 and read_loop reads and writes this many
  # files causing the build to time out
  - ulimit -n 256
  - make test

jobs:
  include:
    - stage: documentation
      # freezing the python2.7 version fot this at first
      python:
        - "2.7"
      env:  # serial version of QUIP
        - QUIP_ARCH=linux_x86_64_gfortran QUIP_INC=Makefile.inc

      install: # packages for building docs
        - sudo apt-get install -y
            libgsl0-dev
            libxpm-dev
            pandoc
        
        - pip install
            ase==3.17.0
            docutils==0.14
            sphinx
            sphinx-rtd-theme
            nbsphinx
            numpydoc

        # needed to nbconvert ipynb files and to process the rst files
        - pip install 'nbconvert[execute]' 'ipython<6'

        # quippy is working, install it
        - make &> /dev/null
        - make install-quippy &> /dev/null

        # Install atomeye from src
        - export QUIP_ROOT=`pwd`
        - git clone https://github.com/jameskermode/AtomEye.git src/AtomEye
        - cd src/AtomEye/Python
        - python setup.py install
        - cd ../../..

      script:
        - cd doc
        - make html

      deploy:
        provider: pages
        local_dir: doc/_build/html
        skip-cleanup: true
        github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
        keep-history: true
        on:
          branch: public

    - stage: release
      env:  # serial version of QUIP
        - QUIP_ARCH="" QUIP_INC=""
      addons:
        apt:
          update: false
      before_install: skip
      install: skip
      script:
        - curl -i http://www.libatoms.org/gap/cgi-bin/update.cgi

    - stage: docker
      name: "Trigger for building docker images"
      env:  # serial version of QUIP
        - QUIP_ARCH="" QUIP_INC=""
      addons:
        apt:
          update: false
      before_install: skip
      install: skip
      script:
        - wget --quiet --header="Content-Type: application/json" --header="Accept: application/json" --header="Travis-API-Version: 3" --header="Authorization: token $TRAVIS_TOKEN" --post-data '{"request": {"branch": "public"}}' 'https://api.travis-ci.org/repo/libatoms%2Fquip-docker/requests'

notifications:
 email:
   - quip-developers@eng.cam.ac.uk

