language: python
env: 
  - QUIP_ARCH=linux_x86_64_gfortran BUILD=VANILLA
  - QUIP_ARCH=linux_x86_64_gfortran_openmp BUILD=VANILLA
  - QUIP_ARCH=linux_x86_64_gfortran_openmpi BUILD=VANILLA
  - QUIP_ARCH=linux_x86_64_gfortran BUILD=ALL_NOEXTERNAL
  - QUIP_ARCH=linux_x86_64_gfortran_openmp BUILD=ALL_NOEXTERNAL
  - QUIP_ARCH=linux_x86_64_gfortran_openmpi BUILD=ALL_NOEXTERNAL
python:
  - 2.6
  - 2.7
install:
  # Make the build directory manually for rules
  - mkdir -p build/${QUIP_ARCH}
  # Copy the rules file (rather than make config)
  - cp tests/rules/${BUILD}_Makefile.${QUIP_ARCH}.inc build/${QUIP_ARCH}/Makefile.inc
  # Compile QUIP
  - make
  - make libquip
  # Fetch and install ASE for quippy
  - git clone https://gitlab.com/ase/ase.git
  - cd ase; pip install .; cd ..
  # Build quippy bindings
  - make quippy
script:
  - ulimit -a
  # Sometimes file limit is 64000 and read_loop reads and writes this many files 
  # causing the build to time out
  - ulimit -n 256
  # Quippy should be built -> start tests
  - travis_wait make test
addons:
  apt:
    packages:
    - gfortran
    - liblapack-dev
    - libblas-dev
    - python-numpy
    - openmpi-bin
    - libopenmpi-dev
    - netcdf-bin
    - libnetcdf-dev
    - libhdf5-serial-dev
