---
language: python
python:
  - '2.7'

branches:
  only:
    - public

env:  # only serial version of QUIP
  - QUIP_ARCH=linux_x86_64_gfortran

addons:
  apt:
    update: true
    packages: # pandoc is required for nbconvert in docs; gsl and xpm are for atomeye.
    - gfortran
    - libblas-dev
    - liblapack-dev
    - openmpi-bin
    - libopenmpi-dev
    - netcdf-bin
    - libnetcdf-dev
    - libhdf5-serial-dev
    - libgsl0-dev
    - libxpm-dev
    - python-numpy
    - pandoc

before_install:
  - echo ${QUIP_ARCH}

  - pip install ase

  # Make the build directory manually for rules
  - mkdir -p build/${QUIP_ARCH}

  # Copy the rules file (rather than make config)
  - cp travis/Makefile.inc build/${QUIP_ARCH}/Makefile.inc

  - gfortran --version
  - gcc --version
  - g++ --version
  - python --version
  - pip freeze --all

install: # Compile QUIP, libquip and quippy, if a non-skipped build.
  # stdout is redirected as it generates too much output.
  - make > /dev/null
  - make libquip > /dev/null
  - make quippy > /dev/null

script: # Quippy should have built successfully -> start tests
  - make test

## Public and private docker images with GAP, pushed from here
## Strip ThirdParty from the public image
#jobs:
#  include:
#    - stage: generate documetation
#
#      before_install:
#        - sudo apt-get install -y pandoc
#
#      install: # packages for building docs
#        - pip install
#            sphinx
#            sphinx-rtd-theme
#            nbsphinx
#            numpydoc
#
#        # needed to nbconvert ipynb files and to process the rst files
#        - pip install 'nbconvert[execute]' 'ipython<6'
#
#        # quippy is working, install it
#        - make install-quippy
#
#        # Install atomeye from src
#        - git clone https://github.com/jameskermode/AtomEye.git src/AtomEye
#        - cd src/AtomEye/Python && python setup.py install
#
#      script:
#        - cd docs; make html
#
#      deploy:
#        provider: pages
#        local_dir: docs/_build/html
#        skip-cleanup: true
#        github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
#        keep-history: true
#        on:
#          branch: master
#
#notifications:
#  email:
#    - quip-developers@eng.cam.ac.uk

