# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the public branch
  push:
    branches: [ public ]
  pull_request:
    branches: [ public ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      # Runs a set of commands using the runners shell
      - name: Build and test QUIP
        run: |
          export QUIP_ARCH=linux_x86_64_gfortran QUIP_INC=Makefile.inc
          sudo apt-get update -y
          sudo apt-get install -y  gfortran libblas-dev liblapack-dev \
            openmpi-bin libopenmpi-dev netcdf-bin libnetcdf-dev libhdf5-serial-dev \
            python-numpy
          mkdir -p build/${QUIP_ARCH}
          cp travis/${QUIP_INC} build/${QUIP_ARCH}/Makefile.inc
          make
          make libquip
          make quippy
          make install-quippy
          ulimit -n 256
          make test

      - name: Build documentation  
        run:
          sudo apt-get install -y libgsl0-dev libxpm-dev pandoc
          cd doc
          make html
          
      - name: Deploy documentation
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/public'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_build/html    
