# This builds the QUIP docker image, tagging it as development
#   since the main docker run is only happening on the public
#   branch after merge is completed, you can use this for
#   building a development version of the docker, triggered
#   manually when needed
name: Build QUIP Docker image

# manually triggered only
on: [ workflow_dispatch ]

jobs:

  docker:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # with dev tag for now
      - name: Build quip
        run: |
          docker build --tag libatomsquip/quip:dev docker
          docker push libatomsquip/quip:dev
