name: Build QUIP Docker image

# change this to the public one later on!
on: [ push, workflow_dispatch ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # with dev tag for now
      - name: Build quip
        run: |
          docker build --tag libatomsquip/quip:dev docker
          docker push libatomsquip/quip:dev
