name: Build QUIP Docker image

# change this to the public one later on!
on: [ push, pull_request, workflow_dispatch ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Pull the latest version of the image
      # in order to use unchanged layers
      - name: pull last version of image
        run: docker pull libatomsquip/quip:latest || true

      # iwth dev flag for now
      - name: Build quip
        run: |
          docker build --tag libatomsquip/quip:dev --cache-from libatomsquip/quip docker
          docker push libatomsquip/quip:dev
